List<String> returnindex = [
  'Shoulder',
  'Full Length',
   'Shoulder Gap',
  'Sleeves Length',
  'Armhole Round',
   'Circle Down Loose',
  'Sleeves Round',
  'Upper Chest Round',
  'Lower Chest Round',
  'Waist Round',
   'First Dart Point',
   'Second Dart Point',
  'Bust Point',
   'Front AC',
  'Front Neck Deep',
  'Back Neck Deep',
  'Waist Band Length',
  'Neck Width',
  'Hip',
  'Waist Length',
  'Slit Length',
  'Bottom Round',
  'Chest Round',
  'Back Neck Width',
];

List<String> returnindexonlybottommeasurement = [
  'Full Length',
  'Waist Band',
  'Hip',
  'Thigh Round',
  'Knee Round',
  'Knee Length',
  'Crotch Length',
  'Anckle Round',
];